//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class ProjectRegistrationForm extends JPanel {
    private JButton jcomp1;
    private JTextField fullName;
    private JTextField username;
    private JTextField jcomp4;
    private JLabel jcomp5;
    private JLabel jcomp6;
    private JLabel jcomp7;
    private JLabel jcomp8;
    private JLabel displayRegistration;

    public ProjectRegistrationForm() {
        //construct components
        jcomp1 = new JButton ("Register");
        fullName = new JTextField (5);
        username = new JTextField (5);
        jcomp4 = new JTextField (5);
        jcomp5 = new JLabel ("Full Name");
        jcomp6 = new JLabel ("Username");
        jcomp7 = new JLabel ("Syndicate");
        jcomp8 = new JLabel ("   REGISTRATION FORM");
        displayRegistration = new JLabel ("");

        //adjust size and set layout
        setPreferredSize (new Dimension (452, 366));
        setLayout (null);

        //add components
        add (jcomp1);
        add (fullName);
        add (username);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (displayRegistration);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (180, 270, 85, 35);
        fullName.setBounds (140, 135, 160, 20);
        username.setBounds (140, 185, 160, 20);
        jcomp4.setBounds (140, 235, 160, 20);
        jcomp5.setBounds (140, 110, 100, 25);
        jcomp6.setBounds (140, 160, 100, 25);
        jcomp7.setBounds (140, 210, 100, 25);
        jcomp8.setBounds (150, 45, 140, 40);
        displayRegistration.setBounds (140, 315, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("ProjectRegistrationForm");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new ProjectRegistrationForm());
        frame.pack();
        frame.setVisible (true);
    }
}
